/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ModeloRouteImport } from './routes/modelo'
import { Route as MissaoVisaoRouteImport } from './routes/missao-visao'
import { Route as DiferenciaisRouteImport } from './routes/diferenciais'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as BeneficiosRouteImport } from './routes/beneficios'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminParceirosRouteImport } from './routes/admin.parceiros'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminDefinicoesRouteImport } from './routes/admin.definicoes'
import { Route as AdminConteudosRouteImport } from './routes/admin.conteudos'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeloRoute = ModeloRouteImport.update({
  id: '/modelo',
  path: '/modelo',
  getParentRoute: () => rootRouteImport,
} as any)
const MissaoVisaoRoute = MissaoVisaoRouteImport.update({
  id: '/missao-visao',
  path: '/missao-visao',
  getParentRoute: () => rootRouteImport,
} as any)
const DiferenciaisRoute = DiferenciaisRouteImport.update({
  id: '/diferenciais',
  path: '/diferenciais',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosRoute = BeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParceirosRoute = AdminParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDefinicoesRoute = AdminDefinicoesRouteImport.update({
  id: '/definicoes',
  path: '/definicoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudosRoute = AdminConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beneficios': typeof BeneficiosRoute
  '/contactos': typeof ContactosRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/missao-visao': typeof MissaoVisaoRoute
  '/modelo': typeof ModeloRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/conteudos': typeof AdminConteudosRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beneficios': typeof BeneficiosRoute
  '/contactos': typeof ContactosRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/missao-visao': typeof MissaoVisaoRoute
  '/modelo': typeof ModeloRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/conteudos': typeof AdminConteudosRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beneficios': typeof BeneficiosRoute
  '/contactos': typeof ContactosRoute
  '/diferenciais': typeof DiferenciaisRoute
  '/missao-visao': typeof MissaoVisaoRoute
  '/modelo': typeof ModeloRoute
  '/quem-somos': typeof QuemSomosRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/conteudos': typeof AdminConteudosRoute
  '/admin/definicoes': typeof AdminDefinicoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/parceiros': typeof AdminParceirosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/beneficios'
    | '/contactos'
    | '/diferenciais'
    | '/missao-visao'
    | '/modelo'
    | '/quem-somos'
    | '/servicos'
    | '/sitemap.xml'
    | '/admin/conteudos'
    | '/admin/definicoes'
    | '/admin/leads'
    | '/admin/parceiros'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beneficios'
    | '/contactos'
    | '/diferenciais'
    | '/missao-visao'
    | '/modelo'
    | '/quem-somos'
    | '/servicos'
    | '/sitemap.xml'
    | '/admin/conteudos'
    | '/admin/definicoes'
    | '/admin/leads'
    | '/admin/parceiros'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/beneficios'
    | '/contactos'
    | '/diferenciais'
    | '/missao-visao'
    | '/modelo'
    | '/quem-somos'
    | '/servicos'
    | '/sitemap.xml'
    | '/admin/conteudos'
    | '/admin/definicoes'
    | '/admin/leads'
    | '/admin/parceiros'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BeneficiosRoute: typeof BeneficiosRoute
  ContactosRoute: typeof ContactosRoute
  DiferenciaisRoute: typeof DiferenciaisRoute
  MissaoVisaoRoute: typeof MissaoVisaoRoute
  ModeloRoute: typeof ModeloRoute
  QuemSomosRoute: typeof QuemSomosRoute
  ServicosRoute: typeof ServicosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelo': {
      id: '/modelo'
      path: '/modelo'
      fullPath: '/modelo'
      preLoaderRoute: typeof ModeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missao-visao': {
      id: '/missao-visao'
      path: '/missao-visao'
      fullPath: '/missao-visao'
      preLoaderRoute: typeof MissaoVisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diferenciais': {
      id: '/diferenciais'
      path: '/diferenciais'
      fullPath: '/diferenciais'
      preLoaderRoute: typeof DiferenciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios': {
      id: '/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof BeneficiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parceiros': {
      id: '/admin/parceiros'
      path: '/parceiros'
      fullPath: '/admin/parceiros'
      preLoaderRoute: typeof AdminParceirosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/definicoes': {
      id: '/admin/definicoes'
      path: '/definicoes'
      fullPath: '/admin/definicoes'
      preLoaderRoute: typeof AdminDefinicoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudos': {
      id: '/admin/conteudos'
      path: '/conteudos'
      fullPath: '/admin/conteudos'
      preLoaderRoute: typeof AdminConteudosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConteudosRoute: typeof AdminConteudosRoute
  AdminDefinicoesRoute: typeof AdminDefinicoesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminParceirosRoute: typeof AdminParceirosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConteudosRoute: AdminConteudosRoute,
  AdminDefinicoesRoute: AdminDefinicoesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminParceirosRoute: AdminParceirosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BeneficiosRoute: BeneficiosRoute,
  ContactosRoute: ContactosRoute,
  DiferenciaisRoute: DiferenciaisRoute,
  MissaoVisaoRoute: MissaoVisaoRoute,
  ModeloRoute: ModeloRoute,
  QuemSomosRoute: QuemSomosRoute,
  ServicosRoute: ServicosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
